# These are supported funding model platforms

# Contributors:
# - mrhenrike (Principal contributor and maintainer)
# - bhbrandon (Contributor)
# 
# Organization: Uniao-Geek (União Geek)
# Project: SOC Detection Laboratory
# Description: Modern cybersecurity lab environment for threat detection, hunting, and SOC training