# These are supported funding model platforms

github: mrhenrike # GitHub Sponsors - Principal sponsor da Uniao-Geek
thanks_dev: bhrandon # thanks.dev username (if applicable)

# Contributors:
# - mrhenrike (Principal contributor and maintainer)
# - bhbrandon (Contributor)
# 
# Organization: Uniao-Geek (União Geek)
# Project: SOC Detection Laboratory
# Description: Modern cybersecurity lab environment for threat detection, hunting, and SOC training
